version: "3.4"

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ..:/var/www/html

  nginx:
    build:
      context: ./nginx
    ports:
      - "8000:80"
    volumes:
      - ..:/var/www/html

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: db_password
      POSTGRES_USER: db
    volumes:
      - ./database_data:/var/lib/postgresql/data:rw
